UserJaPerson/Models/DataFile.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserJaPerson.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataFile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataFile()
        {
            this.People = new HashSet<Person>();
        }
    
        public int Id { get; set; }
        public byte[] Content { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public System.DateTime Created { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Person> People { get; set; }
    }
}

UserJaPerson/Controllers/DataFilesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using UserJaPerson.Models;

namespace UserJaPerson.Models
{
    public class DataFileInfo // selle klassi tegin, et ei peaks kõiki faile andmebaasist lugema
    // selles klassis on KÕIK andmebaasi väljad peale faili sisu
    {
        public int Id { get; set; }
        public string ContentType { get; set; }
        public string FileName { get; set; }
        public System.DateTime Created { get; set; }

        // sellise asja lisasin, et saaks hõlpsasti seda tüüpi objekte teha
        // oleks võinud selle asemel ka konstruktorit kasutada

        //public static explicit operator DataFileInfo ((int id, string contentType, string fileName, System.DateTime created) info)
        //    => new DataFileInfo { Id = info.id, ContentType = info.contentType, Created = info.created, FileName = info.fileName};

        // sama asi siis contruktorina oleks
        //public DataFileInfo() { } // default contruktor, et ei peaks ogu aeg
        //public DataFileInfo((int id, string contentType, string fileName, System.DateTime created) info)
        //    => (Id, ContentType, FileName, Created) = info;

        // NB! tuplit kasutan siin parameetrina, et saaks lühemalt kirjutada
    }
}

namespace UserJaPerson.Controllers
{
    public class DataFilesController : MyController
    {
 
        // GET: DataFiles
        public ActionResult Index()
        {
            string database = (Request.Params["db"] ?? Session["db"] ?? null)?.ToString()??"Northwind";
            Session["db"] = database;
            

            Dictionary<string, string> databases = new Dictionary<string, string>
            {
                {"Henn", "Northwind" },
                {"Huvikool", "Tagarida" },
                {"Eelarveldajad", "Budget" },
                {"Puhkajad", "TooJaVile" },
                {"Fotostuudiod", "FBR" },
                {"Koerajalutajad", "Patrull" },
                {"Reisimehed", "KolmTenorit" },
                {"Aednikud", "Aednikud" }

            };
            ViewBag.db = new SelectList(databases, "Value", "Key", database);

            var q = db.DataFiles.Select(x => new { x.Id, x.Created, x.ContentType, x.FileName })
                .ToList()
                //.Select(x => (DataFileInfo)(x.Id, x.FileName, x.ContentType, x.Created))
                //.Select(x => new DataFileInfo((x.Id, x.FileName, x.ContentType, x.Created)))
                .Select(x => new DataFileInfo { Id = x.Id, FileName = x.FileName, ContentType = x.ContentType, Created = x.Created })
                .ToList();
            return View(q);
        }

        // GET: DataFiles/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            
            DataFile dataFile = db.DataFiles.Find(id);
            if (dataFile == null)
            {
                return HttpNotFound();
            }
            return View(dataFile);
        }

        // GET: DataFiles/Create
 
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UserJaPerson/Controllers/MyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserJaPerson.Models;
using System.IO;
using System.Data.SqlClient;

namespace UserJaPerson.Controllers
{
    public class MyController : Controller
    {
        // TODO: muuda ära dataContext
        // datacontexti access võix olla protected, 
        // siis saavad MyController tüüpi kontrollerid seda sama datacontexti kasutada
        NorthwindEntities ldb = null;
        protected NorthwindEntities db => ldb ?? (ldb = new NorthwindEntities(
            Session["db"]?.ToString() ?? "Northwind"
            ));

        

        // võtsin selle rea ära, et saaks erinevates andmebaasides kolada
        // panin tagasi, muutsin Param = "*" ja lisasin teise parameetri
        // muidu tulid teise andmebaasi sama numbriga failid cacheist
        [OutputCache(Duration =3600, VaryByParam = "*", Location = System.Web.UI.OutputCacheLocation.Any)]
        public ActionResult Content(int? id,string database)
        {
            
            DataFile df = db.DataFiles.Find(id);
            if (df == null) return HttpNotFound();
            return File(df.Content, df.ContentType);
        }
        
        protected Person CurrentPerson = null; // siis on hea kohe see PersonObject omale taskusse panna
        protected void CheckPerson()
        {
           
            if (Request.IsAuthenticated)        // kontrollida vaja vaid siis
                if ((CurrentPerson?.EMail ?? "") != User.Identity.Name)    // kui juba ei ole meeles või on vale
                    {
                        CurrentPerson = db.People.Where(x => x.EMail == User.Identity.Name).SingleOrDefault();
                        if (CurrentPerson == null)
                        {
                            using (ApplicationDbContext dba = new ApplicationDbContext())
                            {
                                ApplicationUser u = dba.Users.Where(x => x.Email == User.Identity.Name).SingleOrDefault();
                                db.People.Add(CurrentPerson = new Person
                                {
                                    EMail = User.Identity.Name,
                                    FirstName = u.FirstName,
                                    LastName = u.LastName,
                                    BirthDate = u.BirthDate
                                });
                                db.SaveChanges();
                            }
                        }
                    }
                else CurrentPerson = null;
        }

        // file - kontrollerisse post-requestiga üles laetud fail
        // oldId - vana faili number, mis baasist kustutada (null - mitte kustutada
        // change - tegevus, mis lisamise ja kustutamise vahel vaja teha
        //  x => {person.PictureId = x; db.SaveChanges();}
        protected void ChangeDataFile(HttpPostedFileBase file, Action<int> change, int? oldId)
        {
            if (file != null && file.ContentLength > 0)
                using (BinaryReader br = new BinaryReader(file.InputStream))
                {
                    DataFile df = new DataFile
                    {
                        Content = br.ReadBytes(file.ContentLength),
                        FileName = file.FileName.Split('\\').Last().Split('/').Last(),
                        ContentType = file.ContentType,
                        Created = DateTime.Now
                    };
                    db.DataFiles.Add(df);
                    db.SaveChanges();
                    change(df.Id);
                    if (oldId.HasValue)
                    {
                        db.DataFiles.Remove(db.DataFiles.Find(oldId.Value));
                        db.SaveChanges();
                    }

                }
        }

    }

}

UserJaPerson/Views/DataFiles/Create.cshtml
@model UserJaPerson.Models.DataFile

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DataFile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UserJaPerson/Views/DataFiles/Delete.cshtml
@model UserJaPerson.Models.DataFile

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DataFile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

UserJaPerson/Views/DataFiles/Details.cshtml
@model UserJaPerson.Models.DataFile

@{
    ViewBag.Title = "Details";
    string database = Session["db"]?.ToString() ?? "Northwind"; // cache'i juhtimiseks
}

<h2>Details</h2>

<div>
    <h4>DataFile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd> @*see parameeter database on Cache juhtimiseks*@
            <img src="@Url.Action("Content", "My", new { id=Model.Id, database })" height="300" />
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContentType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContentType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Created)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Created)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

UserJaPerson/Views/DataFiles/Edit.cshtml
@model UserJaPerson.Models.DataFile

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>DataFile</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Content, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Content, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ContentType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ContentType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ContentType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Created, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Created, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Created, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

UserJaPerson/Views/DataFiles/Index.cshtml
@model IEnumerable<UserJaPerson.Models.DataFileInfo>

@{
    ViewBag.Title = "Index";
    string database = Session["db"].ToString(); // cache'i juhtimiseks
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

<form name="myForm" action="/DataFiles/Index" method="post">
    @Html.DropDownList("db", null, htmlAttributes: new { onchange="document.myForm.submit()" })
    <input type="submit" value="vaata" />
</form>

<table class="table">
    <tr>
        
        <th>
            @Html.DisplayNameFor(model => model.ContentType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Created)
        </th>
        <th>Pilt</th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.ContentType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Created)
        </td>
        <td> @*see parameeter database on Cache'i juhtimiseks*@
            <img src="@Url.Action("Content","My",new { id = item.Id, database })" height="200" />
        </td>

        <td>
            @*@Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) |*@
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>